name: "Build"

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: "Install Build Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: "Build Firmware and Apps"
        run: |
          ./fbt COMPACT=1 DEBUG=0 --with-updater updater_package fap_dist

      - name: "Collect Artifacts"
        run: |
          mkdir -p release_artifacts
          cp -v build/f7-firmware-C/firmware.bin release_artifacts/flipper-z-f7-firmware-oled.bin || true
          cp -v build/f7-firmware-C/firmware.dfu release_artifacts/flipper-z-f7-firmware-oled.dfu || true
          cp -v build/f7-firmware-C/firmware.hex release_artifacts/flipper-z-f7-firmware-oled.hex || true
          cp -v dist/f7-C/*.tgz release_artifacts/ || true
          cp -v dist/f7-C/*.zip release_artifacts/ || true

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: flipper-oled-build
          path: release_artifacts/*
